spring.application.name=bff-operacion

server.port=8082

# JWT Secret temporal!!!
jwt.secret=navium-secret-key-2024-super-segura

# URL microservicios temporaaal!!!!
navium.ms.andenes.url=http://localhost:8080
navium.ms.contenedores.url=http://localhost:8081
navium.ms.agendamiento.url=http://localhost:8083

# circuit breaker defaults
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

resilience4j.circuitbreaker.instances.andenesCb.baseConfig=default
resilience4j.circuitbreaker.instances.contenedoresCb.baseConfig=default
resilience4j.circuitbreaker.instances.agendamientoCb.baseConfig=default
