spring.application.name=bff-operacion
spring.main.allow-bean-definition-overriding=true

server.port=8086

# Clave secreta para firmar y validar los JWT (protegida)
jwt.secret=${JWT_SECRET:NaviumSuperSecretKeyParaFirmaDeTokens2026!}

# URL microservicios
navium.ms.andenes.url=${API_ANDENES_URL}
navium.ms.contenedores.url=${API_CONTENEDORES_URL}
navium.ms.agendamiento.url=${API_AGENDAMIENTOS_URL}

# circuit breaker defaults
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

resilience4j.circuitbreaker.instances.andenesCb.baseConfig=default
resilience4j.circuitbreaker.instances.contenedoresCb.baseConfig=default
resilience4j.circuitbreaker.instances.agendamientoCb.baseConfig=default
resilience4j.circuitbreaker.instances.usuariosCb.baseConfig=default
